export default [
    // 获取 account list
    'FETCH_ACCOUNT_LIST_DATA',
    'FETCH_ACCOUNT_LIST_DATA_SUCCESS',
    'FETCH_ACCOUNT_LIST_DATA_FAIL',

    // 创建 account
    'CREATE_ACCOUNT',
    'CREATE_ACCOUNT_SUCCESS',
    'CREATE_ACCOUNT_FAIL',

    // 更新 account
    'UPDATE_ACCOUNT',
    'UPDATE_ACCOUNT_SUCCESS',
    'UPDATE_ACCOUNT_FAIL',

    // 获取一个 account detail
    'FETCH_ACCOUNT_DETAIL',
    'FETCH_ACCOUNT_DETAIL_SUCCESS',
    'FETCH_ACCOUNT_DETAIL_FAIL',

    // 删除一个 account
    'DELETE_ACCOUNT',
    'DELETE_ACCOUNT_SUCCESS',
    'DELETE_ACCOUNT_FAIL'
];
