export default [
    // 获取 ARTICLE list
    'FETCH_ARTICLE_LIST_DATA',
    'FETCH_ARTICLE_LIST_DATA_SUCCESS',
    'FETCH_ARTICLE_LIST_DATA_FAIL',

    'FETCH_ARTICLE_DETAIL_SUCCESS',

    'CREATE_ARTICLE',
    'CREATE_ARTICLE_SUCCESS',
    'CREATE_ARTICLE_FAIL'
];
