export default [
    // 获取 STUDENT list
    'FETCH_CLAZZ_LIST_DATA',
    'FETCH_CLAZZ_LIST_DATA_SUCCESS',
    'FETCH_CLAZZ_LIST_DATA_FAIL',

    'CREATE_CLAZZ',
    'CREATE_CLAZZ_SUCCESS',
    'CREATE_CLAZZ_FAIL',

    'UPDATE_CLAZZ',
    'UPDATE_CLAZZ_SUCCESS',
    'UPDATE_CLAZZ_FAIL'
];
