export default [
    // 获取 COURSE list
    'FETCH_COURSE_LIST_DATA',
    'FETCH_COURSE_LIST_DATA_SUCCESS',
    'FETCH_COURSE_LIST_DATA_FAIL',

    'FETCH_COURSE_DETAIL',
    'FETCH_COURSE_DETAIL_SUCCESS',
    'FETCH_COURSE_DETAIL_FAIL',

    'CREATE_COURSE',
    'CREATE_COURSE_SUCCESS',
    'CREATE_COURSE_FAIL',

    'UPDATE_COURSE',
    'UPDATE_COURSE_SUCCESS',
    'UPDATE_COURSE_FAIL',

    'REMOVE_CACHE_COURSE'
];
