export default [
    'FETCH_CS_LIST_DATA',
    'FETCH_CS_DATA_SUCCESS',
    'FETCH_CS_DATA_FAIL',

    'UPDATE_CS_DATA',
    'UPDATE_CS_DATA_SUCCESS',
    'UPDATE_CS_DATA_FAIL',

    'FETCH_CS_DETAIL',
    'FETCH_CS_DETAIL_SUCCESS',
    'FETCH_CS_DETAIL_FAIL',

    'CREATE_CS',
    'CREATE_CS_SUCCESS',
    'CREATE_CS_FAIL',

    'CS_ADD_COURSE',
    'CS_ADD_COURSE_SUCCESS',
    'CS_ADD_COURSE_FAIL',

    'CS_REMOVE_COURSE',
    'CS_REMOVE_COURSE_SUCCESS',
    'CS_REMOVE_COURSE_FAIL'
];
