export default [
    // 获取 STUDENT list
    'FETCH_STUDENT_LIST_DATA',
    'FETCH_STUDENT_LIST_DATA_SUCCESS',
    'FETCH_STUDENT_LIST_DATA_FAIL',

    // 创建 STUDENT
    'CREATE_STUDENT',
    'CREATE_STUDENT_SUCCESS',
    'CREATE_STUDENT_FAIL',

    // 更新 STUDENT
    'UPDATE_STUDENT',
    'UPDATE_STUDENT_SUCCESS',
    'UPDATE_STUDENT_FAIL',

    // 获取一个 STUDENT detail
    'FETCH_STUDENT_DETAIL',
    'FETCH_STUDENT_DETAIL_SUCCESS',
    'FETCH_STUDENT_DETAIL_FAIL',

    // 删除一个 STUDENT
    'DELETE_STUDENT',
    'DELETE_STUDENT_SUCCESS',
    'DELETE_STUDENT_FAIL'
];
